### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by higps** [Zabaniya001/att_firering#1]
When I set it in the code like this

TF2CustAttr_SetString(Weapon1, "fire ring attribute", "max_rage=1000.0 damage=70.0 radius=150.0 duration=10.0");

Where Weapon1 is a flamethrower, nothing happens, no errors.

It works if using another weapon like a scorch shot, but when activating it causes segmentation fault on the server

**Comment by tsuza** [comment]
Mh, the plugin as far as I know is still working on the server that it's in. Could you pass the error log / crash dump link?

**Comment by higps** [comment]
https://crash.limetech.org/o7mcescm3uug

**Comment by higps** [comment]
It still crashes when used, also doesn't initialize correctly when applied to spawned weapons

**Comment by tsuza** [comment]
I've pushed an update where I switched away from `TF2Wearable` to `TF2Utils `and from `CGlobalEntityList::FindEntityInSphere()` to `TR_EnumerateEntitiesSphere`. Tested it on my Windows server and it works. Let me know.

**Comment by higps** [comment]
> I've pushed an update where I switched away from `TF2Wearable` to `TF2Utils `and from `CGlobalEntityList::FindEntityInSphere()` to `TR_EnumerateEntitiesSphere`. Tested it on my Windows server and it works. Let me know.

Tested on Linux and nothing happens, the plugin loads, but there is no hud or anything resembling any functionality from the plugin

**Comment by tsuza** [comment]
When are you giving the attribute to the weapon? In this plugin, the "attribute check" logic happens on `post_inventory_application` and `SDKHook_WeaponEquipPost`.

**Comment by higps** [comment]
I am applying it during the item's creation.

If I use the custom weapon adapter it works.

With my Manned Machines mod, weapons are created on a frame after the players spawn, Other custom attributes work with my mod, so there's something with the way yours checks, or stops to check that makes it do nothing. I guess I can modify it so it checks after the weapon has gotten it's attributes though.

**Comment by higps** [comment]
I modified it with using a requestframe from the inventory post check and then it worked
